s3 bits

diff --git a/workspaces/diff-engine/Taskfile.yml b/workspaces/diff-engine/Taskfile.yml
--- a/workspaces/diff-engine/Taskfile.yml
+++ b/workspaces/diff-engine/Taskfile.yml
@@ -133,3 +133,40 @@ tasks:
           BUILD_ARGS: "{{.RELEASE_BUILD_ARGS}}"
       - task: :flush-to-disk
       - task: locate-binaries
+
+  package-tarballs:
+    summary: |
+      Locates any previously built diff-engine binaries and creates a tgz archive
+      for each in ./build/dist. The structure of the tarball is expected to be:
+
+        tar tvf build/dist/optic_diff-v0.0.0-alpha.b00-macos.tar.gz
+        drwxr-xr-x  0 nate   staff       0 Feb 23 15:14 optic_diff-v0.0.0-alpha.b00-macos/
+        -rwxr-xr-x  0 nate   staff 12298919 Feb 23 15:14 optic_diff-v0.0.0-alpha.b00-macos/optic_diff
+    vars:
+      VERSION: '{{.VERSION}}'
+    cmds:
+      # kind of a hack job. but it mimics the existing tags we're appending to the binary tarballs
+      # in the main release flow.
+      - |
+        for binary in $(task diff-engine:locate-binaries)
+        do
+          if [[ $binary =~ "x86_64-apple" ]]; then
+            tag="macos"
+          elif [[ $binary =~ "aarch64-apple" ]]; then
+            tag="macos-aarch64"
+          elif [[ $binary =~ "windows" ]]; then
+            tag="win64"
+          elif [[ $binary =~ "linux" ]]; then
+            tag="linux"
+          else
+            echo "Could not identify the arch for file: $binary"
+            exit 1
+          fi
+
+          filename="optic_diff-v{{.VERSION}}-$tag"
+          chmod +x $binary
+          mkdir -p build/$filename build/dist
+          cp $binary build/$filename/
+          tar -C build -czvf build/dist/${filename}.tar.gz $filename
+        done
+      - ls -lh build/dist
